# @package task
# AKI prediction using KDIGO criteria (binary classification)
# Predict if patient will develop acute kidney injury

task_name: aki_kdigo
task_type: binary
n_classes: null
head_type: mlp
hidden_dims: [64]
dropout: 0.1
activation: relu
use_layer_norm: false
projection_dim: null
