# @package task
# Hospital mortality prediction (binary classification)
# Predict if patient will die before hospital discharge

task_name: mortality_hospital
task_type: binary
n_classes: null
head_type: mlp
hidden_dims: [64]
dropout: 0.1
activation: relu
use_layer_norm: false
projection_dim: null
